---
-
  name: 'Install NGINX based on the linux type'
  hosts: all
  tasks: 
    - name: Install Debian
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian" and
            ansible_distribution_version == "16.04"
            
    - name: Install RedHat
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat" or
            ansible_os_family == "Centos"

